### PR TITLE
Fix handling default arguments in ensureIndex

### PR DESCRIPTION
**Pull request by ForbesLindesay**
I don't think it should be calling createIndex.

### CODE REVIEW

**Comment by saintedlama** [comment]
I'm not sure what this pull request should fix or change

**Comment by ForbesLindesay** [comment]
currently, if you omit one of the optional arguments when calling `ensureIndex`, instead of filling in the default args and calling `ensureIndex` recursively (like all other methods do), this one calls `createIndex`.    I strongly suspect that's a result of accidentally copy and paste.  I can't figure out why else it would be like this.

**Comment by saintedlama** [comment]
Thanks, I should learn to read diffs :smile:

**Comment by saintedlama** [comment]
2.2.2 released on npm :shipit:

**Comment by ForbesLindesay** [comment]
:+1:

**Pull request merged**
