### PR TITLE
Make `Bulk.toString()` actually return a string

### PR DESCRIPTION
**Pull request by ForbesLindesay**
Before this change it returns an object, which seems confusing.

### CODE REVIEW

**Comment by saintedlama** [comment]
This PR breaks the tests a bit

**Comment by ForbesLindesay** [comment]
I've updated the test.  Hopefully that will fix it.

**Comment by saintedlama** [comment]
Still no luck with the pull request. Tests are failing. You can run `npm test` locally to see if code style conforms to standard code style.

**Comment by ForbesLindesay** [comment]
Updated

**Pull request merged**
