### PR TITLE
Added support for finalize in mapReduce

### PR DESCRIPTION
**Pull request by mortenanders**

### CODE REVIEW

**Comment by saintedlama** [comment]
Merging the pull request fails due to code style violations. Will merge if code style violations are fixed

**Comment by mortenanders** [comment]
Sorry. Overlooked running standard on collection.js. Should be ok now. Travis still fails though, but that seems to be due to other reasons?

**Comment by mortenanders** [comment]
Sorry about the hassle, but it seems like the travis job is broken as it cannot fetch 'mongodb-org-server'.

**Comment by saintedlama** [comment]
Why did you close the issue? Due to the travis problems? I guess this is a temporary issue :smile_cat: @ travis

**Comment by watson** [comment]
@saintedlama Regarding Travis, then it was an issue with apt-get. I've updated the `.travis.yml` file, so now Travis should build correctly again. I've seen a few instances though where one of the test cases trips over its own feet, but you can just re-run that particular one for now (this is unrelated to the `.travis.yml` update, just thought I'd mention it now we're talking tests)

**Comment by mortenanders** [comment]
Yes, I got a little discouraged with the travis' builds breaking. And since I am not very familiar with it.

I will reopen it later today and see if the changes by @watson help me out :+1:

**Pull request closed without merging**
