### PR TITLE
Add support for ScramSHA1

### PR DESCRIPTION
**Pull request by dustinblackman**
Add support to connect using different authentication mechanisms with a new options argument. 
Fixes: https://github.com/mafintosh/mongojs/issues/208

A PR has also been made to prevent having to requiring in ScramSHA1. 
https://github.com/christkv/mongodb-core/pull/28

### CODE REVIEW

**Comment by Chris911** [comment]
Please take a look at this as soon as possible. SCRAM-SHA-1 is the default mechanism for MongoDB versions beginning with the 3.0 series: http://docs.mongodb.org/manual/core/authentication/#scram-sha-1-and-existing-user-credentials

**Comment by dustinblackman** [comment]
Bump.

**Comment by mafintosh** [comment]
@saintedlama thoughts on this?

**Comment by saintedlama** [comment]
Looks quite ok, some code style issues and we don't have any tests for the auth feature at all. :+1: for a merge and npm release to get the feature out and fix other stuff later on.

**Comment by saintedlama** [comment]
@watson @mafintosh @sorribas Shall we merge? I could fix some stylistic issues.

**Comment by watson** [comment]
:+1:

**Comment by Chris911** [comment]
We've been using this in production for about 2 weeks now without issues.

**Comment by mafintosh** [comment]
@saintedlama :+1: go ahead and merge

**Comment by saintedlama** [comment]
I'm offline the next days. will merge on Friday :8ball:

**Pull request merged**
