### PR TITLE
Added back tailable cursor support.

### PR DESCRIPTION
**Pull request by mcollina**
It follows the same pattern documented in the README.

BTW, what's missing for a full 1.0.0 release?

### CODE REVIEW

**Comment by mafintosh** [comment]
Looks good to me. @sorribas maintains this project so he probably has insights into what is missing.

**Comment by mafintosh** [comment]
@mcollina this seems to be failing on travis for some reason. does it work locally?

**Comment by sorribas** [comment]
The test fail with mongodb 2.4, which We should probably drop support for in the latest versions of mongojs.

**Comment by sorribas** [comment]
We have to fix travis to reflect this. I'll do this.

**Comment by sorribas** [comment]
Published as 1.0.0

**Comment by mcollina** [comment]
AWESOME!
Il giorno mer 10 giu 2015 alle 20:05 Eduardo Sorribas <
notifications@github.com> ha scritto:

**Pull request merged**
